# Generated by Django 4.0.6 on 2022-07-17 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=234)),
                ('image', models.ImageField(upload_to='')),
                ('hover_image', models.ImageField(upload_to='')),
                ('description', models.TextField()),
            ],
        ),
    ]
