# Generated by Django 4.0.6 on 2022-07-25 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_category_comment_order_alter_product_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_availabele',
            new_name='is_available',
        ),
    ]
