ORDER_STATUS_PENDING = 'P'
ORDER_STATUS_SHIPPING = 'SH'
ORDER_STATUS_COMPLETE = 'C'

ORDER_STATUS_CHOICES = [
    (ORDER_STATUS_PENDING, 'Pending'),
    (ORDER_STATUS_COMPLETE, 'Complete'),
    (ORDER_STATUS_SHIPPING, 'Shipping'),
]
